import { resolve } from 'node:path';
import { parseArgs } from 'node:util';
import { writeFileSync } from 'node:fs';
import { createBacktestApp } from '../../backtest/cli-app.js';
import { WalkForwardService } from '../../backtest/walkforward/walkforward.service.js';
import { pointInTime } from '../../strategies/rotation/rotation-universe.js';
import type { StrategyBar } from '../../strategies/strategy.types.js';
import { INDEX_SYMBOLS, PROFILES, type ProfileSleeve } from '../profiles.js';
import { SAFE_ASSET } from '../universe.js';
import { painStats } from './pain-stats.js';
import { curveStats, mixedCurve, type Curve } from './profile-stats.js';
import { sp500Top } from './sp500-universe.js';
import { yahooDaily } from './yahoo-history.js';

/**
 * Tests every risk profile the same fair way (each year's 50 most-traded
 * S&P 500 members, walk-forward 2y/6m, Yahoo prices) and, with --save,
 * writes the numbers to src/broker/profile-stats.data.ts (commit it), where the broker shows them.
 *   node dist/broker/lab/profiles.cli.js --save
 */
const { values } = parseArgs({
  options: {
    from: { type: 'string', default: '2005-01-01' },
    save: { type: 'boolean', default: false },
  },
});
const from = new Date(values.from);
const to = new Date();
const cache = resolve(process.cwd(), '.cache/yahoo');
const app = await createBacktestApp();
const sp500 = await sp500Top(
  50,
  from,
  to,
  resolve(process.cwd(), '.cache/sp500/sp500_ticker_start_end.csv'),
  cache,
);
const stocks = [...sp500.symbols, SAFE_ASSET];
const bars: Record<string, StrategyBar[]> = await yahooDaily(
  [...stocks, ...INDEX_SYMBOLS],
  from,
  to,
  cache,
);
const market = { SPY: bars.SPY };

const runs = new Map<string, Curve[]>();
async function sleeveCurve(s: ProfileSleeve): Promise<Curve[]> {
  const key = JSON.stringify([s.kind, s.params]);
  const known = runs.get(key);
  if (known) return known;
  const symbols = s.kind === 'momentum' ? stocks : INDEX_SYMBOLS;
  pointInTime.set(s.kind === 'momentum' ? sp500.allowed : null);
  const r = await app.get(WalkForwardService).run(
    {
      strategies: ['momentum-rotation'],
      grid: Object.fromEntries(
        Object.entries(s.params).map(([k, v]) => [k, [v]]),
      ),
      symbols,
      timeframe: '1Day',
      from,
      to,
      train: '2y',
      test: '6m',
      sort: 'return-dd',
      initialCash: 10_000,
      slippageBps: 5,
      feePerShare: 0,
      cashYieldPct: 3,
    },
    Object.fromEntries(symbols.map((x) => [x, bars[x] ?? []])),
    market,
  );
  runs.set(key, r.equityCurve);
  return r.equityCurve;
}

const pct = (n: number) => `${n >= 0 ? '+' : ''}${n.toFixed(1)}%`;
const docs = [];
for (const p of PROFILES) {
  const parts = await Promise.all(
    p.sleeves.map(async (s) => ({
      curve: await sleeveCurve(s),
      weight: s.weightPct / 100,
    })),
  );
  const curve = mixedCurve(parts);
  const stats = curveStats(curve);
  const spyCurve = bars.SPY.filter(
    (b) => b.timestamp >= stats.from && b.timestamp <= stats.to,
  ).map((b) => ({ timestamp: b.timestamp, equity: b.close }));
  const pain = painStats(curve, spyCurve);
  const spy = { ...curveStats(spyCurve), pain: painStats(spyCurve) };
  console.log(
    `${p.name.padEnd(11)} ${pct(stats.annualPct)}/yr  worst drop -${stats.maxDrawdownPct.toFixed(1)}%  worst year ${stats.worstYear.year} ${pct(stats.worstYear.pct)}  best ${stats.bestYear.year} ${pct(stats.bestYear.pct)}  up years ${stats.positiveYearsPct.toFixed(0)}%   (SPY ${pct(spy.annualPct)}/yr, -${spy.maxDrawdownPct.toFixed(1)}%)`,
  );
  const months = (m: number) => `${(m / 12).toFixed(1)}y`;
  console.log(
    `${''.padEnd(11)} calmar ${pain.calmar.toFixed(2)} (SPY ${spy.pain.calmar.toFixed(2)})  ulcer ${pain.ulcerIndex.toFixed(1)} (SPY ${spy.pain.ulcerIndex.toFixed(1)})  longest under water ${months(pain.longestUnderwaterMonths)} (SPY ${months(spy.pain.longestUnderwaterMonths)})  trailed SPY in ${pain.vsSpy3y?.trailedPct.toFixed(0)}% of 3-year stretches, worst ${pain.vsSpy3y?.worstGapPct.toFixed(1)} pts/yr`,
  );
  docs.push({
    _id: p.id,
    ...stats,
    pain,
    spy,
    method: `Walk-forward (settings picked on 2 years, scored on the 6 months after), ${stats.from.getUTCFullYear()}-${stats.to.getUTCFullYear()}`,
    universe:
      "Each year's 50 most-traded S&P 500 members (Yahoo prices; delisted companies missing)",
  });
}
if (values.save) {
  // Committed with the code: every environment has the same numbers (no database step).
  const file = resolve(process.cwd(), 'src/broker/profile-stats.data.ts');
  const round = (_: string, v: unknown) =>
    typeof v === 'number' ? Math.round(v * 100) / 100 : v;
  writeFileSync(
    file,
    `// Generated by \`node dist/broker/lab/profiles.cli.js --save\` (the algo lab). Do not edit by hand.\n` +
      `import type { ProfileStatsFile } from './profile-stats.types.js';\n\n` +
      `export const PROFILE_STATS: ProfileStatsFile = ${JSON.stringify({ testedAt: new Date(), profiles: Object.fromEntries(docs.map(({ _id, ...d }) => [_id, d])) }, round, 2)};\n`,
  );
  console.log(`Wrote ${file}: commit it.`);
}
await app.close();
