import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import type { ProfileRobustnessFile } from '../profile-stats.types.js';
import { percentile, type RobustPart } from './robust-stats.js';

const pct = (n: number) => `${n >= 0 ? '+' : ''}${n.toFixed(1)}%`;

/** Merges the robustness parts in `dir` into src/broker/profile-robustness.data.ts (commit it). */
export function saveRobustness(dir: string): void {
  const parts = readdirSync(dir)
    .filter((f) => f.endsWith('.json'))
    .map(
      (f) => JSON.parse(readFileSync(resolve(dir, f), 'utf8')) as RobustPart,
    );
  const base = parts.find((p) => p.periods);
  if (!base?.periods || !base.tVsSpy)
    throw new Error('Run --part periods first');
  const file: ProfileRobustnessFile = {
    testedAt: new Date(),
    method:
      'the same 2005–today test rerun with the weekly re-rank on each day of the week, and 8 times without a random 20% of the stocks',
    profiles: Object.fromEntries(
      ['aggressive', 'balanced', 'careful'].map((id) => {
        const runs = parts.flatMap((p) => p.variations[id] ?? []);
        const annual = runs.map((r) => r.annualPct);
        const spy = base.periods?.spy ?? [];
        return [
          id,
          {
            usualPct: [percentile(annual, 0.25), percentile(annual, 0.75)],
            worstDropPct: Math.max(...runs.map((r) => r.maxDrawdownPct)),
            runs: runs.length,
            periods: (base.periods?.[id] ?? []).map((p, i) => ({
              ...p,
              spyPct: spy[i]?.pct ?? 0,
            })),
            tVsSpy: base.tVsSpy?.[id] ?? 0,
          },
        ];
      }),
    ),
  };
  const round = (_: string, v: unknown) =>
    typeof v === 'number' ? Math.round(v * 100) / 100 : v;
  const out = resolve(process.cwd(), 'src/broker/profile-robustness.data.ts');
  writeFileSync(
    out,
    `// Generated by \`node dist/broker/lab/robust.cli.js --part save\` (the algo lab). Do not edit by hand.\n` +
      `import type { ProfileRobustnessFile } from './profile-stats.types.js';\n\n` +
      `export const PROFILE_ROBUSTNESS: ProfileRobustnessFile = ${JSON.stringify(file, round, 2)};\n`,
  );
  for (const [id, r] of Object.entries(file.profiles))
    console.log(
      `${id.padEnd(11)} usually ${pct(r.usualPct[0])} to ${pct(r.usualPct[1])}/yr, worst drop -${r.worstDropPct.toFixed(1)}% (${r.runs} runs), t vs SPY ${r.tVsSpy.toFixed(2)}`,
    );
  console.log(`Wrote ${out}: commit it.`);
}
