/**
 * Finance words the general-purpose AFINN list (used by the `sentiment`
 * library) scores wrong or not at all, e.g. "falls", "downgrade", "beats".
 * Scores -5..5 like AFINN. Inspired by the Loughran-McDonald finance lists.
 */
export const FINANCE_WORDS: Record<string, number> = {
  // Price moves
  soar: 3,
  soars: 3,
  soaring: 3,
  surge: 3,
  surges: 3,
  surging: 3,
  jump: 2,
  jumps: 2,
  rally: 2,
  rallies: 2,
  climb: 1,
  climbs: 1,
  gain: 1,
  gains: 1,
  rise: 1,
  rises: 1,
  rebound: 1,
  rebounds: 1,
  record: 1,
  high: 0,
  fall: -2,
  falls: -2,
  falling: -2,
  drop: -2,
  drops: -2,
  slump: -3,
  slumps: -3,
  plunge: -3,
  plunges: -3,
  tumble: -3,
  tumbles: -3,
  sink: -2,
  sinks: -2,
  slide: -2,
  slides: -2,
  sell: -1,
  selloff: -3,
  'sell-off': -3,
  crash: -4,
  crashes: -4,
  decline: -2,
  declines: -2,
  low: -1,
  lower: -1,
  higher: 1,
  // Results and guidance
  beat: 2,
  beats: 2,
  tops: 2,
  exceeds: 2,
  outperform: 2,
  outperforms: 2,
  strong: 2,
  raises: 2,
  miss: -2,
  misses: -2,
  missed: -2,
  weak: -2,
  cuts: -2,
  cut: -2,
  slashes: -3,
  warns: -2,
  warning: -2,
  guidance: 0,
  shortfall: -3,
  loss: -2,
  losses: -2,
  profit: 2,
  profits: 2,
  profitable: 2,
  growth: 2,
  // Analysts
  upgrade: 2,
  upgrades: 2,
  upgraded: 2,
  overweight: 1,
  buy: 1,
  bullish: 2,
  'price target': 0,
  downgrade: -2,
  downgrades: -2,
  downgraded: -2,
  underweight: -1,
  bearish: -2,
  neutral: 0,
  // Company events
  lawsuit: -2,
  lawsuits: -2,
  sues: -2,
  sued: -2,
  probe: -2,
  investigation: -2,
  antitrust: -2,
  fine: -1,
  fined: -2,
  recall: -2,
  recalls: -2,
  layoffs: -2,
  bankruptcy: -4,
  default: -3,
  fraud: -4,
  delay: -1,
  delays: -1,
  buyback: 2,
  dividend: 1,
  approval: 2,
  approved: 2,
  partnership: 1,
  launch: 1,
  launches: 1,
  // Words AFINN scores positively but that are neutral in finance headlines
  share: 0,
  shares: 0,
  stock: 0,
  price: 0,
  target: 0,
  top: 0,
  like: 0,
  please: 0,
};
