// Generated by `node dist/broker/lab/profiles.cli.js --save` (the algo lab). Do not edit by hand.
import type { ProfileStatsFile } from './profile-stats.types.js';

export const PROFILE_STATS: ProfileStatsFile = {
  testedAt: '2026-10-06T08:41:39.242Z',
  profiles: {
    aggressive: {
      from: '2007-01-03T00:00:00.000Z',
      to: '2026-10-05T00:00:00.000Z',
      totalPct: 2764.53,
      annualPct: 18.51,
      maxDrawdownPct: 45.86,
      worstYear: {
        year: 2008,
        pct: -37.39,
      },
      bestYear: {
        year: 2024,
        pct: 77.17,
      },
      positiveYearsPct: 72.22,
      years: [
        {
          year: 2007,
          pct: 25.55,
        },
        {
          year: 2008,
          pct: -37.39,
        },
        {
          year: 2009,
          pct: 11.84,
        },
        {
          year: 2010,
          pct: 19.21,
        },
        {
          year: 2011,
          pct: -3.92,
        },
        {
          year: 2012,
          pct: 14.11,
        },
        {
          year: 2013,
          pct: 45.12,
        },
        {
          year: 2014,
          pct: 14.92,
        },
        {
          year: 2015,
          pct: 4.85,
        },
        {
          year: 2016,
          pct: -1.63,
        },
        {
          year: 2017,
          pct: 27.31,
        },
        {
          year: 2018,
          pct: -7.26,
        },
        {
          year: 2019,
          pct: 40.5,
        },
        {
          year: 2020,
          pct: 56.72,
        },
        {
          year: 2021,
          pct: 4.01,
        },
        {
          year: 2022,
          pct: -15.82,
        },
        {
          year: 2023,
          pct: 32.09,
        },
        {
          year: 2024,
          pct: 77.17,
        },
        {
          year: 2025,
          pct: 35.48,
        },
        {
          year: 2026,
          pct: 100.81,
        },
      ],
      spy: {
        from: '2007-01-03T00:00:00.000Z',
        to: '2026-10-05T00:00:00.000Z',
        totalPct: 685.64,
        annualPct: 11,
        maxDrawdownPct: 55.19,
        worstYear: {
          year: 2008,
          pct: -36.8,
        },
        bestYear: {
          year: 2013,
          pct: 32.31,
        },
        positiveYearsPct: 83.33,
        years: [
          {
            year: 2007,
            pct: 5.33,
          },
          {
            year: 2008,
            pct: -36.8,
          },
          {
            year: 2009,
            pct: 26.35,
          },
          {
            year: 2010,
            pct: 15.06,
          },
          {
            year: 2011,
            pct: 1.89,
          },
          {
            year: 2012,
            pct: 15.99,
          },
          {
            year: 2013,
            pct: 32.31,
          },
          {
            year: 2014,
            pct: 13.46,
          },
          {
            year: 2015,
            pct: 1.23,
          },
          {
            year: 2016,
            pct: 12,
          },
          {
            year: 2017,
            pct: 21.71,
          },
          {
            year: 2018,
            pct: -4.57,
          },
          {
            year: 2019,
            pct: 31.22,
          },
          {
            year: 2020,
            pct: 18.33,
          },
          {
            year: 2021,
            pct: 28.73,
          },
          {
            year: 2022,
            pct: -18.18,
          },
          {
            year: 2023,
            pct: 26.18,
          },
          {
            year: 2024,
            pct: 24.89,
          },
          {
            year: 2025,
            pct: 17.72,
          },
          {
            year: 2026,
            pct: 14.51,
          },
        ],
      },
      method:
        'Walk-forward (settings picked on 2 years, scored on the 6 months after), 2007-2026',
      universe:
        "Each year's 50 most-traded S&P 500 members (Yahoo prices; delisted companies missing)",
    },
    balanced: {
      from: '2007-01-03T00:00:00.000Z',
      to: '2026-10-05T00:00:00.000Z',
      totalPct: 1481.5,
      annualPct: 15,
      maxDrawdownPct: 32.32,
      worstYear: {
        year: 2022,
        pct: -19.11,
      },
      bestYear: {
        year: 2024,
        pct: 69.27,
      },
      positiveYearsPct: 77.78,
      years: [
        {
          year: 2007,
          pct: 7.35,
        },
        {
          year: 2008,
          pct: -1.71,
        },
        {
          year: 2009,
          pct: 18.56,
        },
        {
          year: 2010,
          pct: 3.9,
        },
        {
          year: 2011,
          pct: 0.19,
        },
        {
          year: 2012,
          pct: 9.84,
        },
        {
          year: 2013,
          pct: 41.65,
        },
        {
          year: 2014,
          pct: 13.09,
        },
        {
          year: 2015,
          pct: -7.38,
        },
        {
          year: 2016,
          pct: 3.53,
        },
        {
          year: 2017,
          pct: 28.03,
        },
        {
          year: 2018,
          pct: -5.02,
        },
        {
          year: 2019,
          pct: 21.39,
        },
        {
          year: 2020,
          pct: 38.64,
        },
        {
          year: 2021,
          pct: 5.89,
        },
        {
          year: 2022,
          pct: -19.11,
        },
        {
          year: 2023,
          pct: 21.47,
        },
        {
          year: 2024,
          pct: 69.27,
        },
        {
          year: 2025,
          pct: 13.9,
        },
        {
          year: 2026,
          pct: 75.36,
        },
      ],
      spy: {
        from: '2007-01-03T00:00:00.000Z',
        to: '2026-10-05T00:00:00.000Z',
        totalPct: 685.64,
        annualPct: 11,
        maxDrawdownPct: 55.19,
        worstYear: {
          year: 2008,
          pct: -36.8,
        },
        bestYear: {
          year: 2013,
          pct: 32.31,
        },
        positiveYearsPct: 83.33,
        years: [
          {
            year: 2007,
            pct: 5.33,
          },
          {
            year: 2008,
            pct: -36.8,
          },
          {
            year: 2009,
            pct: 26.35,
          },
          {
            year: 2010,
            pct: 15.06,
          },
          {
            year: 2011,
            pct: 1.89,
          },
          {
            year: 2012,
            pct: 15.99,
          },
          {
            year: 2013,
            pct: 32.31,
          },
          {
            year: 2014,
            pct: 13.46,
          },
          {
            year: 2015,
            pct: 1.23,
          },
          {
            year: 2016,
            pct: 12,
          },
          {
            year: 2017,
            pct: 21.71,
          },
          {
            year: 2018,
            pct: -4.57,
          },
          {
            year: 2019,
            pct: 31.22,
          },
          {
            year: 2020,
            pct: 18.33,
          },
          {
            year: 2021,
            pct: 28.73,
          },
          {
            year: 2022,
            pct: -18.18,
          },
          {
            year: 2023,
            pct: 26.18,
          },
          {
            year: 2024,
            pct: 24.89,
          },
          {
            year: 2025,
            pct: 17.72,
          },
          {
            year: 2026,
            pct: 14.51,
          },
        ],
      },
      method:
        'Walk-forward (settings picked on 2 years, scored on the 6 months after), 2007-2026',
      universe:
        "Each year's 50 most-traded S&P 500 members (Yahoo prices; delisted companies missing)",
    },
    careful: {
      from: '2007-01-03T00:00:00.000Z',
      to: '2026-10-05T00:00:00.000Z',
      totalPct: 808.59,
      annualPct: 11.82,
      maxDrawdownPct: 23.44,
      worstYear: {
        year: 2022,
        pct: -16.68,
      },
      bestYear: {
        year: 2024,
        pct: 47.62,
      },
      positiveYearsPct: 72.22,
      years: [
        {
          year: 2007,
          pct: 1.33,
        },
        {
          year: 2008,
          pct: -1.49,
        },
        {
          year: 2009,
          pct: 20.3,
        },
        {
          year: 2010,
          pct: 1.47,
        },
        {
          year: 2011,
          pct: -3.69,
        },
        {
          year: 2012,
          pct: 10.55,
        },
        {
          year: 2013,
          pct: 34.95,
        },
        {
          year: 2014,
          pct: 9.77,
        },
        {
          year: 2015,
          pct: -6.51,
        },
        {
          year: 2016,
          pct: 8.43,
        },
        {
          year: 2017,
          pct: 23.99,
        },
        {
          year: 2018,
          pct: -6.51,
        },
        {
          year: 2019,
          pct: 19.52,
        },
        {
          year: 2020,
          pct: 23.83,
        },
        {
          year: 2021,
          pct: 17.64,
        },
        {
          year: 2022,
          pct: -16.68,
        },
        {
          year: 2023,
          pct: 18.09,
        },
        {
          year: 2024,
          pct: 47.62,
        },
        {
          year: 2025,
          pct: 11.23,
        },
        {
          year: 2026,
          pct: 43.02,
        },
      ],
      spy: {
        from: '2007-01-03T00:00:00.000Z',
        to: '2026-10-05T00:00:00.000Z',
        totalPct: 685.64,
        annualPct: 11,
        maxDrawdownPct: 55.19,
        worstYear: {
          year: 2008,
          pct: -36.8,
        },
        bestYear: {
          year: 2013,
          pct: 32.31,
        },
        positiveYearsPct: 83.33,
        years: [
          {
            year: 2007,
            pct: 5.33,
          },
          {
            year: 2008,
            pct: -36.8,
          },
          {
            year: 2009,
            pct: 26.35,
          },
          {
            year: 2010,
            pct: 15.06,
          },
          {
            year: 2011,
            pct: 1.89,
          },
          {
            year: 2012,
            pct: 15.99,
          },
          {
            year: 2013,
            pct: 32.31,
          },
          {
            year: 2014,
            pct: 13.46,
          },
          {
            year: 2015,
            pct: 1.23,
          },
          {
            year: 2016,
            pct: 12,
          },
          {
            year: 2017,
            pct: 21.71,
          },
          {
            year: 2018,
            pct: -4.57,
          },
          {
            year: 2019,
            pct: 31.22,
          },
          {
            year: 2020,
            pct: 18.33,
          },
          {
            year: 2021,
            pct: 28.73,
          },
          {
            year: 2022,
            pct: -18.18,
          },
          {
            year: 2023,
            pct: 26.18,
          },
          {
            year: 2024,
            pct: 24.89,
          },
          {
            year: 2025,
            pct: 17.72,
          },
          {
            year: 2026,
            pct: 14.51,
          },
        ],
      },
      method:
        'Walk-forward (settings picked on 2 years, scored on the 6 months after), 2007-2026',
      universe:
        "Each year's 50 most-traded S&P 500 members (Yahoo prices; delisted companies missing)",
    },
  },
};
