// Generated by `node dist/broker/lab/profiles.cli.js --save` (the algo lab). Do not edit by hand.
import type { ProfileStatsFile } from './profile-stats.types.js';

export const PROFILE_STATS: ProfileStatsFile = {
  testedAt: '2026-10-02T12:11:01.940Z',
  profiles: {
    aggressive: {
      from: '2007-01-03T00:00:00.000Z',
      to: '2026-10-01T00:00:00.000Z',
      totalPct: 2751.41,
      annualPct: 18.5,
      maxDrawdownPct: 45.86,
      worstYear: {
        year: 2008,
        pct: -37.39,
      },
      bestYear: {
        year: 2024,
        pct: 77.17,
      },
      positiveYearsPct: 72.22,
      years: [
        {
          year: 2007,
          pct: 25.55,
        },
        {
          year: 2008,
          pct: -37.39,
        },
        {
          year: 2009,
          pct: 11.84,
        },
        {
          year: 2010,
          pct: 19.21,
        },
        {
          year: 2011,
          pct: -3.92,
        },
        {
          year: 2012,
          pct: 14.11,
        },
        {
          year: 2013,
          pct: 45.12,
        },
        {
          year: 2014,
          pct: 14.92,
        },
        {
          year: 2015,
          pct: 4.85,
        },
        {
          year: 2016,
          pct: -1.63,
        },
        {
          year: 2017,
          pct: 27.31,
        },
        {
          year: 2018,
          pct: -7.26,
        },
        {
          year: 2019,
          pct: 40.5,
        },
        {
          year: 2020,
          pct: 56.72,
        },
        {
          year: 2021,
          pct: 4.01,
        },
        {
          year: 2022,
          pct: -15.82,
        },
        {
          year: 2023,
          pct: 32.09,
        },
        {
          year: 2024,
          pct: 77.17,
        },
        {
          year: 2025,
          pct: 35.48,
        },
        {
          year: 2026,
          pct: 99.89,
        },
      ],
      spy: {
        from: '2007-01-03T00:00:00.000Z',
        to: '2026-10-01T00:00:00.000Z',
        totalPct: 674.64,
        annualPct: 10.93,
        maxDrawdownPct: 55.19,
        worstYear: {
          year: 2008,
          pct: -36.79,
        },
        bestYear: {
          year: 2013,
          pct: 32.31,
        },
        positiveYearsPct: 83.33,
        years: [
          {
            year: 2007,
            pct: 5.33,
          },
          {
            year: 2008,
            pct: -36.79,
          },
          {
            year: 2009,
            pct: 26.35,
          },
          {
            year: 2010,
            pct: 15.06,
          },
          {
            year: 2011,
            pct: 1.89,
          },
          {
            year: 2012,
            pct: 15.99,
          },
          {
            year: 2013,
            pct: 32.31,
          },
          {
            year: 2014,
            pct: 13.46,
          },
          {
            year: 2015,
            pct: 1.23,
          },
          {
            year: 2016,
            pct: 12,
          },
          {
            year: 2017,
            pct: 21.71,
          },
          {
            year: 2018,
            pct: -4.57,
          },
          {
            year: 2019,
            pct: 31.22,
          },
          {
            year: 2020,
            pct: 18.33,
          },
          {
            year: 2021,
            pct: 28.73,
          },
          {
            year: 2022,
            pct: -18.18,
          },
          {
            year: 2023,
            pct: 26.18,
          },
          {
            year: 2024,
            pct: 24.89,
          },
          {
            year: 2025,
            pct: 17.72,
          },
          {
            year: 2026,
            pct: 12.91,
          },
        ],
      },
      method:
        'Walk-forward (settings picked on 2 years, scored on the 6 months after), 2007-2026',
      universe:
        "Each year's 50 most-traded S&P 500 members (Yahoo prices; delisted companies missing)",
    },
    growth: {
      from: '2007-01-03T00:00:00.000Z',
      to: '2026-10-01T00:00:00.000Z',
      totalPct: 1752.33,
      annualPct: 15.93,
      maxDrawdownPct: 34.74,
      worstYear: {
        year: 2008,
        pct: -26.55,
      },
      bestYear: {
        year: 2024,
        pct: 61.81,
      },
      positiveYearsPct: 77.78,
      years: [
        {
          year: 2007,
          pct: 16.47,
        },
        {
          year: 2008,
          pct: -26.55,
        },
        {
          year: 2009,
          pct: 14.9,
        },
        {
          year: 2010,
          pct: 13.16,
        },
        {
          year: 2011,
          pct: -5.01,
        },
        {
          year: 2012,
          pct: 13.25,
        },
        {
          year: 2013,
          pct: 40.06,
        },
        {
          year: 2014,
          pct: 12.38,
        },
        {
          year: 2015,
          pct: 1.7,
        },
        {
          year: 2016,
          pct: 2.86,
        },
        {
          year: 2017,
          pct: 25.1,
        },
        {
          year: 2018,
          pct: -7.48,
        },
        {
          year: 2019,
          pct: 33.65,
        },
        {
          year: 2020,
          pct: 42.41,
        },
        {
          year: 2021,
          pct: 11.62,
        },
        {
          year: 2022,
          pct: -15.35,
        },
        {
          year: 2023,
          pct: 26.88,
        },
        {
          year: 2024,
          pct: 61.81,
        },
        {
          year: 2025,
          pct: 27.41,
        },
        {
          year: 2026,
          pct: 72.66,
        },
      ],
      spy: {
        from: '2007-01-03T00:00:00.000Z',
        to: '2026-10-01T00:00:00.000Z',
        totalPct: 674.64,
        annualPct: 10.93,
        maxDrawdownPct: 55.19,
        worstYear: {
          year: 2008,
          pct: -36.79,
        },
        bestYear: {
          year: 2013,
          pct: 32.31,
        },
        positiveYearsPct: 83.33,
        years: [
          {
            year: 2007,
            pct: 5.33,
          },
          {
            year: 2008,
            pct: -36.79,
          },
          {
            year: 2009,
            pct: 26.35,
          },
          {
            year: 2010,
            pct: 15.06,
          },
          {
            year: 2011,
            pct: 1.89,
          },
          {
            year: 2012,
            pct: 15.99,
          },
          {
            year: 2013,
            pct: 32.31,
          },
          {
            year: 2014,
            pct: 13.46,
          },
          {
            year: 2015,
            pct: 1.23,
          },
          {
            year: 2016,
            pct: 12,
          },
          {
            year: 2017,
            pct: 21.71,
          },
          {
            year: 2018,
            pct: -4.57,
          },
          {
            year: 2019,
            pct: 31.22,
          },
          {
            year: 2020,
            pct: 18.33,
          },
          {
            year: 2021,
            pct: 28.73,
          },
          {
            year: 2022,
            pct: -18.18,
          },
          {
            year: 2023,
            pct: 26.18,
          },
          {
            year: 2024,
            pct: 24.89,
          },
          {
            year: 2025,
            pct: 17.72,
          },
          {
            year: 2026,
            pct: 12.91,
          },
        ],
      },
      method:
        'Walk-forward (settings picked on 2 years, scored on the 6 months after), 2007-2026',
      universe:
        "Each year's 50 most-traded S&P 500 members (Yahoo prices; delisted companies missing)",
    },
    balanced: {
      from: '2007-01-03T00:00:00.000Z',
      to: '2026-10-01T00:00:00.000Z',
      totalPct: 1681.79,
      annualPct: 15.71,
      maxDrawdownPct: 29.74,
      worstYear: {
        year: 2022,
        pct: -13.92,
      },
      bestYear: {
        year: 2024,
        pct: 77.17,
      },
      positiveYearsPct: 77.78,
      years: [
        {
          year: 2007,
          pct: 13.31,
        },
        {
          year: 2008,
          pct: -3.08,
        },
        {
          year: 2009,
          pct: 19.91,
        },
        {
          year: 2010,
          pct: 5.18,
        },
        {
          year: 2011,
          pct: 8.81,
        },
        {
          year: 2012,
          pct: 10.2,
        },
        {
          year: 2013,
          pct: 45.12,
        },
        {
          year: 2014,
          pct: 3.1,
        },
        {
          year: 2015,
          pct: -4.83,
        },
        {
          year: 2016,
          pct: 6.42,
        },
        {
          year: 2017,
          pct: 27.31,
        },
        {
          year: 2018,
          pct: -5.42,
        },
        {
          year: 2019,
          pct: 21.73,
        },
        {
          year: 2020,
          pct: 32.11,
        },
        {
          year: 2021,
          pct: 4.01,
        },
        {
          year: 2022,
          pct: -13.92,
        },
        {
          year: 2023,
          pct: 20.35,
        },
        {
          year: 2024,
          pct: 77.17,
        },
        {
          year: 2025,
          pct: 4.45,
        },
        {
          year: 2026,
          pct: 83.39,
        },
      ],
      spy: {
        from: '2007-01-03T00:00:00.000Z',
        to: '2026-10-01T00:00:00.000Z',
        totalPct: 674.64,
        annualPct: 10.93,
        maxDrawdownPct: 55.19,
        worstYear: {
          year: 2008,
          pct: -36.79,
        },
        bestYear: {
          year: 2013,
          pct: 32.31,
        },
        positiveYearsPct: 83.33,
        years: [
          {
            year: 2007,
            pct: 5.33,
          },
          {
            year: 2008,
            pct: -36.79,
          },
          {
            year: 2009,
            pct: 26.35,
          },
          {
            year: 2010,
            pct: 15.06,
          },
          {
            year: 2011,
            pct: 1.89,
          },
          {
            year: 2012,
            pct: 15.99,
          },
          {
            year: 2013,
            pct: 32.31,
          },
          {
            year: 2014,
            pct: 13.46,
          },
          {
            year: 2015,
            pct: 1.23,
          },
          {
            year: 2016,
            pct: 12,
          },
          {
            year: 2017,
            pct: 21.71,
          },
          {
            year: 2018,
            pct: -4.57,
          },
          {
            year: 2019,
            pct: 31.22,
          },
          {
            year: 2020,
            pct: 18.33,
          },
          {
            year: 2021,
            pct: 28.73,
          },
          {
            year: 2022,
            pct: -18.18,
          },
          {
            year: 2023,
            pct: 26.18,
          },
          {
            year: 2024,
            pct: 24.89,
          },
          {
            year: 2025,
            pct: 17.72,
          },
          {
            year: 2026,
            pct: 12.91,
          },
        ],
      },
      method:
        'Walk-forward (settings picked on 2 years, scored on the 6 months after), 2007-2026',
      universe:
        "Each year's 50 most-traded S&P 500 members (Yahoo prices; delisted companies missing)",
    },
    careful: {
      from: '2007-01-03T00:00:00.000Z',
      to: '2026-10-01T00:00:00.000Z',
      totalPct: 869.82,
      annualPct: 12.2,
      maxDrawdownPct: 23.57,
      worstYear: {
        year: 2022,
        pct: -14.08,
      },
      bestYear: {
        year: 2024,
        pct: 51.57,
      },
      positiveYearsPct: 77.78,
      years: [
        {
          year: 2007,
          pct: 4.31,
        },
        {
          year: 2008,
          pct: -2.17,
        },
        {
          year: 2009,
          pct: 20.98,
        },
        {
          year: 2010,
          pct: 2.11,
        },
        {
          year: 2011,
          pct: 0.62,
        },
        {
          year: 2012,
          pct: 10.72,
        },
        {
          year: 2013,
          pct: 36.69,
        },
        {
          year: 2014,
          pct: 4.77,
        },
        {
          year: 2015,
          pct: -5.24,
        },
        {
          year: 2016,
          pct: 9.88,
        },
        {
          year: 2017,
          pct: 23.63,
        },
        {
          year: 2018,
          pct: -6.7,
        },
        {
          year: 2019,
          pct: 19.69,
        },
        {
          year: 2020,
          pct: 20.56,
        },
        {
          year: 2021,
          pct: 16.7,
        },
        {
          year: 2022,
          pct: -14.08,
        },
        {
          year: 2023,
          pct: 17.53,
        },
        {
          year: 2024,
          pct: 51.57,
        },
        {
          year: 2025,
          pct: 6.51,
        },
        {
          year: 2026,
          pct: 46.25,
        },
      ],
      spy: {
        from: '2007-01-03T00:00:00.000Z',
        to: '2026-10-01T00:00:00.000Z',
        totalPct: 674.64,
        annualPct: 10.93,
        maxDrawdownPct: 55.19,
        worstYear: {
          year: 2008,
          pct: -36.79,
        },
        bestYear: {
          year: 2013,
          pct: 32.31,
        },
        positiveYearsPct: 83.33,
        years: [
          {
            year: 2007,
            pct: 5.33,
          },
          {
            year: 2008,
            pct: -36.79,
          },
          {
            year: 2009,
            pct: 26.35,
          },
          {
            year: 2010,
            pct: 15.06,
          },
          {
            year: 2011,
            pct: 1.89,
          },
          {
            year: 2012,
            pct: 15.99,
          },
          {
            year: 2013,
            pct: 32.31,
          },
          {
            year: 2014,
            pct: 13.46,
          },
          {
            year: 2015,
            pct: 1.23,
          },
          {
            year: 2016,
            pct: 12,
          },
          {
            year: 2017,
            pct: 21.71,
          },
          {
            year: 2018,
            pct: -4.57,
          },
          {
            year: 2019,
            pct: 31.22,
          },
          {
            year: 2020,
            pct: 18.33,
          },
          {
            year: 2021,
            pct: 28.73,
          },
          {
            year: 2022,
            pct: -18.18,
          },
          {
            year: 2023,
            pct: 26.18,
          },
          {
            year: 2024,
            pct: 24.89,
          },
          {
            year: 2025,
            pct: 17.72,
          },
          {
            year: 2026,
            pct: 12.91,
          },
        ],
      },
      method:
        'Walk-forward (settings picked on 2 years, scored on the 6 months after), 2007-2026',
      universe:
        "Each year's 50 most-traded S&P 500 members (Yahoo prices; delisted companies missing)",
    },
  },
};
