// Generated by `node dist/broker/lab/robust.cli.js --part save` (the algo lab). Do not edit by hand.
import type { ProfileRobustnessFile } from './profile-stats.types.js';

export const PROFILE_ROBUSTNESS: ProfileRobustnessFile = {
  testedAt: '2026-10-06T08:41:57.374Z',
  method:
    'the same 2005–today test rerun with the weekly re-rank on each day of the week, and 8 times without a random 20% of the stocks',
  profiles: {
    aggressive: {
      usualPct: [15.68, 17.88],
      worstDropPct: 51.09,
      runs: 13,
      periods: [
        {
          from: 2007,
          to: 2012,
          pct: 2.34,
          spyPct: 2.27,
        },
        {
          from: 2013,
          to: 2019,
          pct: 16.18,
          spyPct: 14.19,
        },
        {
          from: 2020,
          to: 2026,
          pct: 37.82,
          spyPct: 15.34,
        },
      ],
      tVsSpy: 1.93,
    },
    balanced: {
      usualPct: [12.07, 14.33],
      worstDropPct: 33.53,
      runs: 9,
      periods: [
        {
          from: 2007,
          to: 2012,
          pct: 6.15,
          spyPct: 2.27,
        },
        {
          from: 2013,
          to: 2019,
          pct: 12.42,
          spyPct: 14.19,
        },
        {
          from: 2020,
          to: 2026,
          pct: 26.43,
          spyPct: 15.34,
        },
      ],
      tVsSpy: 1.02,
    },
    careful: {
      usualPct: [10.33, 11.46],
      worstDropPct: 24.27,
      runs: 9,
      periods: [
        {
          from: 2007,
          to: 2012,
          pct: 4.44,
          spyPct: 2.27,
        },
        {
          from: 2013,
          to: 2019,
          pct: 11.05,
          spyPct: 14.19,
        },
        {
          from: 2020,
          to: 2026,
          pct: 19.68,
          spyPct: 15.34,
        },
      ],
      tVsSpy: 0.21,
    },
  },
};
